networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"

    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

    depends-on:
      - backend
      - client
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev

  client:
    build:
      context: ./client
    networks:
      - dev
