version: "3.9"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - client
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev

  client:
    build:
      context: ./client
    networks:
      - dev
